version: '3'

services:
  #databse
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: examplerootpass
    volumes:
      - db:/var/lib/mysql
    networks:
      - wpnet
  #wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
    networks:
      - wpnet
  #nginx
  web:
    image: nginx
    depends_on:
      - wordpress
    restart: always
    ports:
      - '80:80'
    volumes: 
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - wpnet
volumes:
  db:
  wordpress:
networks:
  wpnet: